
""" Long text used as payload for tests """

LOREM_IPSUM = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque porttitor dui sed ex pulvinar, egestas facilisis ligula elementum. Morbi aliquam eros quis est semper consectetur. Donec laoreet, felis a sodales iaculis, lorem magna dictum tellus, suscipit vestibulum justo quam quis nulla. Donec hendrerit felis eros, et sodales neque lacinia lobortis. Donec diam urna, lacinia eget risus vitae, placerat lobortis dolor. Duis vel facilisis nisi. Phasellus ut nisl nisi. Ut ac velit placerat quam volutpat efficitur. Fusce tellus elit, tempus sit amet arcu et, iaculis accumsan dui.

Donec convallis aliquam tristique. Suspendisse dignissim pulvinar malesuada. Integer ultricies augue vel euismod dignissim. Morbi efficitur rutrum convallis. Donec hendrerit elit ac lectus egestas, vel accumsan mi aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque velit elit, posuere sed lectus et, mattis accumsan erat. Cras eu suscipit est, ac mattis nisl. Aliquam vitae quam nec neque scelerisque accumsan a at ex. Nunc ac sagittis magna, posuere porta dolor. Quisque ut magna enim. Nulla facilisis purus sed tincidunt scelerisque. Duis in lectus bibendum, semper lacus non, mollis risus.

Donec nec nibh et justo pulvinar viverra. Donec egestas leo ut enim maximus sagittis. Sed sem augue, tincidunt id diam non, mollis ultrices elit. Nulla at dapibus justo. Proin id ultrices orci. Donec in felis sit amet tortor euismod maximus. Ut facilisis, erat nec maximus interdum, lacus sapien dapibus lacus, in rutrum augue metus non ligula. Nunc ornare efficitur metus, sodales viverra quam scelerisque eu. Cras quam tortor, pharetra quis risus ac, dignissim eleifend ex. Sed dapibus neque lacus, nec consectetur sapien gravida tincidunt. In aliquam, nulla molestie faucibus malesuada, nisl tortor lacinia mauris, vitae varius augue justo ut tellus. Nulla pretium ullamcorper dui, dictum cursus ex mollis lobortis. Nam et felis sed erat sollicitudin vehicula. Cras suscipit massa id lacus dignissim pulvinar.

Integer bibendum felis sit amet turpis laoreet, vitae sagittis eros eleifend. Praesent pharetra tempor ipsum eget volutpat. In rhoncus risus magna, at tempor orci fringilla in. Integer vel faucibus urna. Vivamus dignissim nec velit at sagittis. Donec fringilla sit amet sapien id cursus. Nam consectetur arcu urna, ac ultrices nisi elementum non. Sed tristique dolor sapien, ut pellentesque est luctus sed. Proin vestibulum, dolor nec aliquet varius, arcu lacus tincidunt diam, at eleifend risus est dictum massa. Nulla sed risus nec dui lobortis maximus ac sit amet turpis. Nunc eros massa, congue in lectus et, aliquet porttitor libero. Integer iaculis ultrices dui eget semper.

Vivamus lobortis fringilla ipsum, sit amet consectetur orci gravida quis. Duis varius urna euismod mauris congue, vel venenatis nunc molestie. Maecenas a dui quis metus tincidunt tristique non sit amet orci. Nullam ipsum leo, maximus in luctus eu, pretium scelerisque nunc. Pellentesque et lectus commodo, mollis augue vitae, mattis nisl. Aenean tincidunt quis felis ac finibus. Maecenas mollis laoreet facilisis. Pellentesque rutrum lorem ut mauris fermentum vulputate. Nam consequat ut velit in vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam auctor arcu auctor, ultricies ante vel, vehicula lorem.

Praesent feugiat massa eget nulla blandit tincidunt. Phasellus at mauris ligula. Integer lectus lorem, dignissim non elementum in, laoreet molestie tortor. Quisque condimentum porttitor odio. Cras ullamcorper porttitor tellus, sed facilisis massa ornare tempus. Aenean at justo metus. Sed vestibulum nisl erat, id euismod lectus fermentum scelerisque. Phasellus semper vel diam id laoreet. Suspendisse at ultrices massa. Proin tristique orci lacus, id mattis libero fringilla nec.

Fusce congue leo nec quam eleifend, vel lobortis dui hendrerit. Nunc odio enim, tincidunt ut dolor ut, tincidunt tristique lacus. Etiam commodo tincidunt dui a rutrum. Integer quis felis ipsum. Sed rhoncus dui non nisl pellentesque auctor. Suspendisse venenatis elit id metus varius, nec venenatis lorem eleifend. Phasellus pulvinar lacinia suscipit. Integer imperdiet sed risus at facilisis. Quisque sit amet quam eu elit mollis placerat. Quisque bibendum ex id leo facilisis, eget tempus turpis bibendum. Aliquam eu augue quis ex gravida mattis. Etiam tincidunt nisi at fermentum efficitur. Duis rhoncus semper ex.

Proin justo nibh, mollis in aliquet nec, fermentum sit amet lorem. Ut pretium dolor id dui consectetur, id dapibus est convallis. Praesent facilisis lorem a nunc elementum, sed elementum sem pellentesque. Nam gravida id massa at ultrices. Sed pellentesque ac lacus ac consequat. Aenean a vestibulum arcu, eu feugiat ipsum. Phasellus tristique condimentum lacus, vitae consequat odio tempor at. Proin viverra vestibulum leo et varius. Nulla faucibus eros sit amet urna fringilla euismod. Nulla vehicula sit amet lectus sit amet elementum.

Vestibulum hendrerit interdum aliquet. Nam egestas felis ut ligula commodo volutpat eu at dui. Etiam vel lacinia ante, sit amet ornare tellus. Praesent sapien leo, blandit eu posuere non, porttitor eu mi. Etiam vel lacinia diam, vel feugiat augue. Vestibulum vulputate a urna eu ullamcorper. Mauris vitae est in quam vulputate dignissim. Maecenas sagittis mollis turpis, at imperdiet purus faucibus at. Nam sodales hendrerit eleifend. In lobortis ante id est aliquam faucibus.

Suspendisse porttitor suscipit dolor eu egestas. Donec sit amet magna molestie, bibendum leo id, scelerisque ante. Maecenas mollis turpis nec iaculis porta. Fusce non venenatis arcu. Donec facilisis dui eu ipsum consectetur, non aliquet neque tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lobortis elit in nunc facilisis, ut tempor sem aliquam.

Nunc a varius justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non euismod risus. Donec auctor nulla eu lorem commodo eleifend. Curabitur mauris neque, molestie quis dapibus a, convallis id enim. Pellentesque efficitur tincidunt pretium. Nam sodales scelerisque felis, a dapibus lacus fermentum eu.

Praesent nec odio posuere, vestibulum sapien eu, scelerisque erat. Nulla efficitur ex nec diam congue luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce quis tortor fermentum, aliquam augue vitae, tincidunt neque. Praesent eu sollicitudin urna. Vestibulum suscipit id sapien id auctor. Quisque eu quam nec felis feugiat facilisis id vel lorem. Donec placerat nisl sed metus faucibus vestibulum. Pellentesque sollicitudin quam eget eros ornare blandit. Nulla vitae mi purus. Vivamus ornare quam vel erat ultrices varius. Donec orci magna, hendrerit vel auctor vel, pharetra sit amet libero. Praesent pretium bibendum malesuada. Morbi lobortis neque et congue viverra.

Pellentesque molestie elit in varius scelerisque. Nam ex felis, tincidunt ac condimentum quis, vestibulum sed risus. Phasellus urna mi, facilisis congue sem non, rhoncus venenatis quam. Nulla euismod magna erat, id hendrerit nisi congue at. Praesent non pretium mi, consectetur dictum elit. Vivamus rutrum risus ut mauris hendrerit iaculis. Ut malesuada turpis dolor, eget hendrerit arcu lobortis efficitur. Ut erat dolor, aliquet ac tempor ac, consectetur quis mauris. Curabitur id consectetur ante, a interdum eros.

Nulla id lobortis tortor. Sed finibus diam eget mi varius convallis. Donec eget hendrerit est. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vestibulum congue nunc vitae sollicitudin. Phasellus lobortis venenatis gravida. Maecenas pellentesque suscipit turpis, a fermentum dui cursus a. In non laoreet risus. Nunc auctor finibus ex eget semper.

Suspendisse potenti. Sed ac efficitur eros. Quisque tincidunt nunc eget mi porta rhoncus. Sed vitae elit lacus. Donec sit amet leo dignissim, dignissim justo at, sodales sapien. Donec faucibus convallis aliquam. Fusce quis elit blandit, dignissim dui convallis, lacinia dolor. Vivamus vehicula nulla sit amet nibh mattis, tincidunt accumsan mi consequat. Aenean malesuada tincidunt pulvinar. Cras vestibulum enim et sem scelerisque, eget feugiat odio euismod.

Nunc laoreet nisl urna, a finibus erat sollicitudin vel. Vivamus a iaculis lacus. Donec posuere id odio venenatis porta. Sed maximus sem sit amet lorem suscipit ultricies nec vel lectus. Maecenas condimentum sed lorem quis tempor. Aenean eu diam eget odio tincidunt semper. Praesent velit orci, rutrum vitae posuere vitae, faucibus at nisl. Nam posuere nibh eget lectus gravida, ac tempus urna posuere. Etiam sodales tellus vel pharetra tempor. Donec vulputate eu neque sed ultrices. Etiam suscipit velit neque, a eleifend leo mattis in. Integer venenatis pellentesque consectetur. Proin elementum magna in mi aliquam facilisis. Donec vel pharetra massa, non mattis odio.

Ut pharetra neque lectus, vitae interdum magna facilisis ut. Vivamus ac tellus vel tellus lacinia ultrices. Pellentesque tincidunt sagittis orci. Morbi sapien nulla, tincidunt nec congue ac, auctor ac diam. Donec ac efficitur odio. Donec venenatis scelerisque justo. Maecenas in commodo lacus. Vivamus efficitur nunc nec ex varius scelerisque. Praesent est quam, venenatis vitae molestie ut, dictum non lectus. Curabitur sed arcu iaculis, hendrerit lorem sit amet, consequat sapien. Maecenas tincidunt condimentum velit, non mattis tortor consectetur laoreet. Praesent efficitur purus in ornare vestibulum. Nam fringilla neque vel odio sagittis, mollis rutrum diam gravida. Nulla facilisi. Suspendisse potenti.

Nullam posuere a justo sit amet tristique. Nunc dapibus venenatis mauris. Ut gravida placerat dui nec interdum. Phasellus dictum lorem vitae malesuada egestas. Praesent commodo fermentum congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vel blandit enim. Quisque sed semper enim, consequat egestas ligula. Nunc quis ipsum blandit erat maximus fermentum efficitur.
"""