/*******************************************************************************
 *
 *  Copyright (c) 2022 Contributors to the Eclipse Foundation
 *
 *  See the LICENSE file(s) distributed with this work for additional
 *  information regarding copyright ownership.
 *
 *  This program and the accompanying materials are made available under the
 *  terms of the Eclipse Public License 1.0
 *  which is available at https://www.eclipse.org/legal/epl-v10.html
 *  and the Eclipse Distribution License v. 1.0
 *  available at http://www.eclipse.org/org/documents/edl-v10.php
 *
 *  SPDX-License-Identifier: EPL-1.0
 *
 *  Contributors:
 *     Jimmy Björklund  - initial version
 *     Achim Kraus      - add getrandom and libcunit
 *
 * dtls_config.h: Generated by cmake from dtls_config.h.cmake.in
 *
 ******************************************************************************/

#warning "DTLS_CONFIG.H IS BEING USED!"

/* Define to 1 if building with ECC support. */
#define DTLS_ECC 1

/* Define to 1 if building with PSK support */
#define DTLS_PSK 0

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "tinydtls"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "tinydtls 0.8.6"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "tinydtls"

/* Define to the home page for this package. */
#define PACKAGE_URL ""

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.8.6"

/* Define WORDS_BIGENDIAN to 1 if your processor stores words with the most
   significant byte first (like Motorola and SPARC, unlike Intel). */
/* #undef WORDS_BIGENDIAN */

/* TODO
   Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.
#ifndef __cplusplus
#undef inline
#endif

   Define to `unsigned int' if <sys/types.h> does not define.
#undef size_t */
