name: Test cases (branch v4)
on: push
jobs:
    test_on_push:
        runs-on: ubuntu-22.04
        steps:
            - name: Check out code with submodules
              uses: actions/checkout@v2
            - name: Building C/C++ parts
              run: |
                   cd test/posix
                   make
            - name: Install Python test dependencies
              run: python3 -m pip install sseclient==0.0.27
            - name: Run tests
              run: |
                   cd test/posix
                   export TRACKLE_ID_LIB_TEST="${{ secrets.TRACKLE_ID_LIB_TEST }}"
                   export TRACKLE_PRIVATE_KEY_LIB_TEST="
                   ${{ secrets.TRACKLE_PRIVATE_KEY_LIB_TEST }}
                   "
                   export TRACKLE_CLIENT_ID_LIB_TEST="${{ secrets.TRACKLE_CLIENT_ID_LIB_TEST }}"
                   export TRACKLE_CLIENT_SECRET_LIB_TEST="${{ secrets.TRACKLE_CLIENT_SECRET_LIB_TEST }}"
                   python3 test.py
            
